pull_request_rules:
  - name: Auto Merge (FILENAME)
    conditions:
      - "status-success=ci/circleci: build"
      - base=master
      - files=FILENAME
      - "#files=1"
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge