pull_request_rules:
  - name: Auto Merge (Electron-OnlineInstaller.csproj‎)
    conditions:
      - "status-success=continuous-integration/appveyor/branch"
      - base=master
      - files=Electron-OnlineInstaller.csproj‎
      - "#files=1"
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge